FROM node:22-alpine

RUN apk add --no-cache openssl

WORKDIR /app

COPY package.json ./

RUN npm install --ignore-scripts

COPY prisma ./prisma
COPY tsconfig.json ./
COPY src ./src

RUN npm run build

RUN npm prune --omit=dev

ENV NODE_ENV=production

CMD ["node", "dist/server.js"]